korea-travel:
  area-code:
    서울: 1
    인천: 2
    대전: 3
    대구: 4
    광주: 5
    부산: 6
    울산: 7
    세종특별자치시: 8
    경기도: 31
    강원특별자치: 32
default-message:
  start: 안녕하세요! 저는 여행 계획 메이트 소소입니다.
  end: 지금까지 여행 계획 메이트 소소였습니다. 제가 필요할 때 또 불러주세요~
  error: 죄송합니다. 봇에 오류가 발생하여 재시도 혹은 고객센터 문의 부탁드립니다.
prompt:
  system:
    kind-planner: 당신은 국내 여행의 일정과 목표 관리를 돕는 조언자로 정확한 계획성이 돋보이는 말투를 사용합니다.
    friendly-planner: 당신은 국내 여행의 일정과 목표 관리를 돕는 친구로 친근한 비격식체 말투를 사용합니다.
gpt:
  model: gpt-4.1
kakaotalk:
  msg-template-id: 120964